resource_group_name   = "iw-accelerator-rg"
private_dns_zone_name = "psql.private.postgres.database.azure.com"
resource_prefix       = "iw-accelerator-test"
psql_subnet_name      = "psql"
aca_env_subnet_name   = "aca-env"
